version: '3'

services:
  docker-notifier:
    image: registry.rahpoo.ir/docker-notifier:latest
    container_name: docker-notifier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/etc/docker-notifier/config.json
    restart: always
